let quotes=[],currentQuoteIndex=0,autoScrollTimer=null,autoplay=false,favorites=new Set(),toastTimer,speechTimer=0,favoritesMode=false;
try{const saved=JSON.parse(localStorage.getItem('sabda-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved)}catch{localStorage.removeItem('sabda-favorites')}
const scroller=document.getElementById('quote-scroller'),toast=document.getElementById('toast'),favoriteCount=document.getElementById('favorite-count'),autoBtn=document.getElementById('autoplay-toggle');
const nepaliDigits=n=>String(n).replace(/\d/g,d=>'०१२३४५६७८९'[d]);
function showToast(m){clearTimeout(toastTimer);toast.textContent=m;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),1600)}
function saveFavorites(){try{localStorage.setItem('sabda-favorites',JSON.stringify([...favorites]))}catch{}if(favoriteCount)favoriteCount.textContent=favorites.size}
function quoteKey(q){return q.id||`${q.quote}::${q.author||''}`}
function isFavorite(q){return favorites.has(quoteKey(q))}
function cardHTML(q,i){const c=document.createElement('article');c.className='quote-card'+(i===currentQuoteIndex?' active':'')+(isFavorite(q)?' favorite-card':'');c.dataset.index=i;c.innerHTML='<button class="favorite-button" type="button" aria-label="मनपर्ने">♥</button><p class="quote-text"></p><p class="quote-author"></p><span class="copy-badge">डबल क्लिक गरेर कपी गर्नुहोस्</span>';c.querySelector('.quote-text').textContent=q.quote;c.querySelector('.quote-author').textContent=q.author||'- लक्ष्मण नेपाल';const f=c.querySelector('.favorite-button');f.classList.toggle('active',isFavorite(q));f.onclick=e=>{e.stopPropagation();toggleFavorite(i)};c.ondblclick=()=>copyQuote(i);return c}
function renderQuotes(){scroller.innerHTML='';if(!quotes.length)return;const frag=document.createDocumentFragment();for(let copy=0;copy<3;copy++)quotes.forEach((q,i)=>frag.appendChild(cardHTML(q,i)));scroller.appendChild(frag);observeCards();saveFavorites();requestAnimationFrame(()=>{const middle=scroller.querySelector(`[data-index="${currentQuoteIndex}"]`);const cards=[...scroller.querySelectorAll(`[data-index="${currentQuoteIndex}"]`)];const target=cards[1]||middle;if(target)target.scrollIntoView({behavior:'auto',block:'center'});updateActiveCards()})}
function toggleFavorite(i){const q=quotes[i],k=quoteKey(q);favorites.has(k)?(favorites.delete(k),showToast('मनपर्नेबाट हटाइयो')):(favorites.add(k),showToast('मनपर्नेमा सुरक्षित भयो'));saveFavorites();scroller.querySelectorAll(`[data-index="${i}"]`).forEach(c=>{c.classList.toggle('favorite-card',favorites.has(k));c.querySelector('.favorite-button').classList.toggle('active',favorites.has(k))})}
async function copyQuote(i=currentQuoteIndex){const q=quotes[i];if(!q)return;const text=`“${q.quote}” ${q.author||''}`;try{await navigator.clipboard.writeText(text)}catch{const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}showToast('उद्धरण कपी भयो ✓')}
function middleCard(i){const cards=scroller.querySelectorAll(`[data-index="${i}"]`);return cards[1]||cards[0]}
function scrollToQuote(i,smooth=true){if(!quotes.length)return;currentQuoteIndex=(i+quotes.length)%quotes.length;const c=middleCard(currentQuoteIndex);if(c)c.scrollIntoView({behavior:smooth?'smooth':'auto',block:'center'});updateActiveCards()}
function nextQuote(){scrollToQuote(currentQuoteIndex+1)}function prevQuote(){scrollToQuote(currentQuoteIndex-1)}
function updateActiveCards(){scroller.querySelectorAll('.quote-card').forEach(c=>c.classList.toggle('active',+c.dataset.index===currentQuoteIndex&&isCentered(c)))}
function isCentered(c){const a=scroller.getBoundingClientRect(),b=c.getBoundingClientRect();return Math.abs((b.top+b.height/2)-(a.top+a.height/2))<b.height*.45}
let observer;function observeCards(){if(observer)observer.disconnect();observer=new IntersectionObserver(es=>{let best=null;es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.65){const r=e.target.getBoundingClientRect(),root=scroller.getBoundingClientRect(),d=Math.abs((r.top+r.height/2)-(root.top+root.height/2));if(!best||d<best.d)best={e,d}}});if(best){const i=+best.e.target.dataset.index;currentQuoteIndex=i;updateActiveCards();if(autoplay&&Date.now()-speechTimer>1200){speechTimer=Date.now();speakCurrent()}}},{root:scroller,threshold:[.65,.8,1]});scroller.querySelectorAll('.quote-card').forEach(c=>observer.observe(c))}
function recenterInfinite(){if(!quotes.length||favoritesMode)return;const max=scroller.scrollHeight-scroller.clientHeight;let target=null;if(scroller.scrollTop<scroller.clientHeight*.15||scroller.scrollTop>max-scroller.clientHeight*.15)target=middleCard(currentQuoteIndex);if(target){scroller.style.scrollBehavior='auto';target.scrollIntoView({block:'center'});scroller.style.scrollBehavior='smooth';updateActiveCards()}}
scroller.addEventListener('scroll',()=>{if(!scroller._edgeFrame){scroller._edgeFrame=requestAnimationFrame(()=>{scroller._edgeFrame=0;recenterInfinite()})}});
function startAutoScroll(){clearInterval(autoScrollTimer);if(autoplay)autoScrollTimer=setInterval(nextQuote,7000)}
function toggleAutoplay(){autoplay=!autoplay;autoBtn.setAttribute('aria-pressed',autoplay);autoBtn.textContent=autoplay?'⏸ Auto':'▶ Auto';if(autoplay)startAutoScroll();else{clearInterval(autoScrollTimer);speechSynthesis?.cancel()}showToast(autoplay?'Auto चालु भयो':'Auto बन्द भयो')}
function speakCurrent(){if(!('speechSynthesis'in window)){showToast('यो ब्राउजरमा आवाज उपलब्ध छैन');return}const q=quotes[currentQuoteIndex];if(!q)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.quote);u.lang='ne-NP';u.rate=.86;u.pitch=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/^ne(-|_)?NP/i.test(v.lang))||voices.find(v=>/^ne/i.test(v.lang))||null;u.onstart=()=>showToast('पढ्दैछ... 🔊');speechSynthesis.speak(u)}
function downloadQuoteAsPNG(){const c=middleCard(currentQuoteIndex);if(!c||typeof html2canvas==='undefined'){showToast('PNG सुविधा अहिले उपलब्ध छैन');return}html2canvas(c,{scale:2,useCORS:true,backgroundColor:'#f5f7fb'}).then(x=>{const a=document.createElement('a');a.download=`laxman-nepal-sabda-${currentQuoteIndex+1}.png`;a.href=x.toDataURL();a.click()}).catch(()=>showToast('PNG बनाउन सकिएन'))}
function toggleFavoritesMode(){favoritesMode=!favoritesMode;document.body.classList.toggle('favorites-mode',favoritesMode);if(favoritesMode&&!favorites.size){showToast('अहिलेसम्म कुनै मनपर्ने छैन');favoritesMode=false;document.body.classList.remove('favorites-mode');return}showToast(favoritesMode?'मनपर्ने उद्धरणहरू':'सबै उद्धरण')}
document.getElementById('next-quote').onclick=nextQuote;document.getElementById('prev-quote').onclick=prevQuote;document.getElementById('copy-quote').onclick=()=>copyQuote();document.getElementById('read-quote').onclick=speakCurrent;document.getElementById('autoplay-toggle').onclick=toggleAutoplay;document.getElementById('download-quote').onclick=downloadQuoteAsPNG;document.getElementById('favorites-toggle').onclick=toggleFavoritesMode;
async function fetchJSON(path){const r=await fetch(`${path}?v=6`,{cache:'no-store'});if(!r.ok)throw Error(`${path}:${r.status}`);return r.json()}
async function loadQuotes(){try{const results=await Promise.allSettled([fetchJSON('./quotes.json'),fetchJSON('./more-quotes.json')]);const all=[];results.forEach(r=>{if(r.status==='fulfilled'&&Array.isArray(r.value))all.push(...r.value)});const seen=new Set();quotes=all.filter(q=>q&&typeof q.quote==='string'&&q.quote.trim()).map(q=>({...q,quote:q.quote.trim(),author:(q.author||'- लक्ष्मण नेपाल').trim()})).filter(q=>{const k=quoteKey(q);if(seen.has(k))return false;seen.add(k);return true});if(!quotes.length)throw Error('empty');currentQuoteIndex=Math.floor(Math.random()*quotes.length);renderQuotes();showToast(`${quotes.length} वटा शब्द तयार छन्`)}catch(e){console.error(e);scroller.innerHTML='<div class="quote-card active"><p class="quote-text">उद्धरण लोड हुन सकेन।</p></div>';showToast('उद्धरण लोड हुन सकेन')}}
loadQuotes();
function renderGreeting(){const h=new Date().getHours(),t=h<=12?'प्रभात':h<=16?'मध्यान्ह':h<=19?'सन्ध्या':'रात्री';document.getElementById('greeting').textContent=`शुभ ${t}`}
function updateNepaliDate(){try{const d=new Date(),bs=NepaliDateConverter.ConvertToNepali(d.getFullYear(),d.getMonth()+1,d.getDate()),m=['बैशाख','जेष्ठ','आषाढ','श्रावण','भाद्र','आश्विन','कार्तिक','मंसिर','पुष','माघ','फाल्गुन','चैत्र'];document.getElementById('nepali-date').textContent=`${m[bs.month-1]} ${nepaliDigits(bs.day)}, ${nepaliDigits(bs.year)}`}catch{}}
function updateClock(){const n=moment().tz('Asia/Kathmandu');document.getElementById('clock').innerHTML=`${n.format('hh')}:${n.format('mm')}:${n.format('ss')}<span id="nampm">${n.format('A')}</span>`}
renderGreeting();updateNepaliDate();updateClock();setInterval(updateClock,1000);setInterval(updateNepaliDate,60000);saveFavorites();
