let quotes=[];let currentQuoteIndex=0;let autoScrollTimer=null;let autoplay=false;let favorites=new Set();let toastTimer;try{const saved=JSON.parse(localStorage.getItem('sabda-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved)}catch{localStorage.removeItem('sabda-favorites')}
const scroller=document.getElementById('quote-scroller'),toast=document.getElementById('toast'),favoriteCount=document.getElementById('favorite-count'),autoBtn=document.getElementById('autoplay-toggle');let favoritesMode=false;
const nepaliDigits=n=>String(n).replace(/\d/g,d=>'०१२३४५६७८९'[d]);function showToast(m){if(!toast)return;clearTimeout(toastTimer);toast.textContent=m;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),1600)}function saveFavorites(){try{localStorage.setItem('sabda-favorites',JSON.stringify([...favorites]))}catch{}if(favoriteCount)favoriteCount.textContent=favorites.size}function quoteKey(q,i){return `${i}:${q.quote}`}function isFavorite(q,i){return favorites.has(quoteKey(q,i))}
function renderQuotes(){scroller.innerHTML='';if(!quotes.length)return;quotes.forEach((q,i)=>{const c=document.createElement('article');c.className='quote-card'+(i===currentQuoteIndex?' active ':'')+(isFavorite(q,i)?' favorite-card':'');c.dataset.index=i;c.innerHTML='<button class="favorite-button" type="button" aria-label="मनपर्ने">♥</button><p class="quote-text"></p><p class="quote-author"></p><span class="copy-badge">डबल क्लिक गरेर कपी गर्नुहोस्</span>';c.querySelector('.quote-text').textContent=q.quote;c.querySelector('.quote-author').textContent=q.author||'- लक्ष्मण नेपाल';const f=c.querySelector('.favorite-button');f.classList.toggle('active',isFavorite(q,i));f.onclick=e=>{e.stopPropagation();toggleFavorite(i)};c.ondblclick=()=>copyQuote(i);scroller.appendChild(c)});observeCards();saveFavorites();scrollToQuote(currentQuoteIndex,false)}
function toggleFavorite(i){const k=quoteKey(quotes[i],i);favorites.has(k)?(favorites.delete(k),showToast('मनपर्नेबाट हटाइयो')):(favorites.add(k),showToast('मनपर्नेमा सुरक्षित भयो'));saveFavorites();const c=scroller.querySelector(`[data-index="${i}"]`);if(c){c.classList.toggle('favorite-card',favorites.has(k));c.querySelector('.favorite-button').classList.toggle('active',favorites.has(k))}}
async function copyQuote(i=currentQuoteIndex){const q=quotes[i];if(!q)return;const text=`“${q.quote}” ${q.author||''}`;try{await navigator.clipboard.writeText(text)}catch{const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}showToast('उद्धरण कपी भयो ✓')}
function scrollToQuote(i,smooth=true){if(!quotes.length)return;currentQuoteIndex=(i+quotes.length)%quotes.length;const c=scroller.querySelector(`[data-index="${currentQuoteIndex}"]`);if(c)c.scrollIntoView({behavior:smooth?'smooth':'auto',block:'center'});updateActiveCards()}function nextQuote(){scrollToQuote(currentQuoteIndex+1)}function prevQuote(){scrollToQuote(currentQuoteIndex-1)}function updateActiveCards(){scroller.querySelectorAll('.quote-card').forEach((c,i)=>c.classList.toggle('active',i===currentQuoteIndex))}
let observer;function observeCards(){if(observer)observer.disconnect();observer=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.65){currentQuoteIndex=+e.target.dataset.index;updateActiveCards();if(autoplay)speakCurrent()}})},{root:scroller,threshold:.65});scroller.querySelectorAll('.quote-card').forEach(c=>observer.observe(c))}
function startAutoScroll(){clearInterval(autoScrollTimer);if(!autoplay)return;autoScrollTimer=setInterval(nextQuote,7000)}function toggleAutoplay(){autoplay=!autoplay;autoBtn.setAttribute('aria-pressed',autoplay);autoBtn.textContent=autoplay?'⏸ Auto':'▶ Auto';autoplay?startAutoScroll():(clearInterval(autoScrollTimer),speechSynthesis.cancel());showToast(autoplay?'Auto चालु भयो':'Auto बन्द भयो')}
function speakCurrent(){if(!('speechSynthesis'in window)){showToast('यो ब्राउजरमा आवाज उपलब्ध छैन');return}const q=quotes[currentQuoteIndex];if(!q)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.quote);u.lang='ne-NP';u.rate=.88;u.pitch=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/^ne(-|_)?NP/i.test(v.lang))||voices.find(v=>/^ne/i.test(v.lang))||null;u.onstart=()=>showToast('पढ्दैछ... 🔊');u.onend=()=>showToast('पढाइ सकियो');speechSynthesis.speak(u)}
function downloadQuoteAsPNG(){const c=scroller.querySelector(`[data-index="${currentQuoteIndex}"]`);if(!c||typeof html2canvas==='undefined')return;html2canvas(c,{scale:2,useCORS:true,backgroundColor:'#f5f7fb'}).then(x=>{const a=document.createElement('a');a.download=`laxman-nepal-sabda-${currentQuoteIndex+1}.png`;a.href=x.toDataURL();a.click()}).catch(()=>showToast('PNG बनाउन सकिएन'))}
function toggleFavoritesMode(){favoritesMode=!favoritesMode;document.body.classList.toggle('favorites-mode',favoritesMode);if(favoritesMode&&!favorites.size){showToast('अहिलेसम्म कुनै मनपर्ने छैन');favoritesMode=false;document.body.classList.remove('favorites-mode');return}showToast(favoritesMode?'मनपर्ने उद्धरणहरू':'सबै उद्धरण');if(favoritesMode){const i=quotes.findIndex((q,n)=>isFavorite(q,n));if(i>=0)scrollToQuote(i,false)}}
document.getElementById('next-quote').onclick=nextQuote;document.getElementById('prev-quote').onclick=prevQuote;document.getElementById('copy-quote').onclick=()=>copyQuote();document.getElementById('read-quote').onclick=speakCurrent;document.getElementById('autoplay-toggle').onclick=toggleAutoplay;document.getElementById('download-quote').onclick=downloadQuoteAsPNG;document.getElementById('favorites-toggle').onclick=toggleFavoritesMode;
async function loadQuotes(){try{const r=await fetch('./quotes.json?v=4',{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();quotes=Array.isArray(d)?d.filter(q=>q&&typeof q.quote==='string'&&q.quote.trim()):[];if(!quotes.length)throw Error('empty');currentQuoteIndex=Math.floor(Math.random()*quotes.length);renderQuotes()}catch(e){console.error(e);scroller.innerHTML='<div class="quote-card active"><p class="quote-text">उद्धरण लोड हुन सकेन।</p></div>';showToast('उद्धरण लोड हुन सकेन')}}loadQuotes();
// Infinite looping: when the user reaches either edge, move to the equivalent quote without a visible end.
scroller.addEventListener('scroll',()=>{if(!quotes.length||favoritesMode)return;const max=scroller.scrollHeight-scroller.clientHeight;if(scroller.scrollTop<8){const target=scroller.querySelector(`[data-index="${quotes.length-2}"]`);if(target){scroller.style.scrollBehavior='auto';target.scrollIntoView({block:'center'});scroller.style.scrollBehavior='smooth'}}else if(scroller.scrollTop>max-8){const target=scroller.querySelector('[data-index="1"]');if(target){scroller.style.scrollBehavior='auto';target.scrollIntoView({block:'center'});scroller.style.scrollBehavior='smooth'}}});
function renderGreeting(){const h=new Date().getHours(),t=h<=12?'प्रभात':h<=16?'मध्यान्ह':h<=19?'सन्ध्या':'रात्री';document.getElementById('greeting').textContent=`शुभ ${t}`}function updateNepaliDate(){try{const d=new Date(),bs=NepaliDateConverter.ConvertToNepali(d.getFullYear(),d.getMonth()+1,d.getDate()),m=['बैशाख','जेष्ठ','आषाढ','श्रावण','भाद्र','आश्विन','कार्तिक','मंसिर','पुष','माघ','फाल्गुन','चैत्र'];document.getElementById('nepali-date').textContent=`${m[bs.month-1]} ${nepaliDigits(bs.day)}, ${nepaliDigits(bs.year)}`}catch{}}function updateClock(){const n=moment().tz('Asia/Kathmandu');document.getElementById('clock').innerHTML=`${n.format('hh')}:${n.format('mm')}:${n.format('ss')}<span id="nampm">${n.format('A')}</span>`}renderGreeting();updateNepaliDate();updateClock();setInterval(updateClock,1000);setInterval(updateNepaliDate,60000);saveFavorites();
