let quotes=[],currentQuoteIndex=0,autoScrollTimer=null,autoplay=false,favorites=new Set(),toastTimer,speechTimer=0,favoritesMode=false;
try{const saved=JSON.parse(localStorage.getItem('sabda-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved)}catch{localStorage.removeItem('sabda-favorites')}
const scroller=document.getElementById('quote-scroller'),toast=document.getElementById('toast'),favoriteCount=document.getElementById('favorite-count'),autoBtn=document.getElementById('autoplay-toggle');
function showToast(m){if(!toast)return;clearTimeout(toastTimer);toast.textContent=m;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),1600)}
function saveFavorites(){try{localStorage.setItem('sabda-favorites',JSON.stringify([...favorites]))}catch{}if(favoriteCount)favoriteCount.textContent=favorites.size}
function quoteKey(q){return q.id||`${q.quote}::${q.author||''}`}function isFavorite(q){return favorites.has(quoteKey(q))}
function cardHTML(q,i){const c=document.createElement('article');c.className='quote-card'+(i===currentQuoteIndex?' active':'')+(isFavorite(q)?' favorite-card':'');c.dataset.index=i;c.innerHTML='<button class="favorite-button" type="button" aria-label="मनपर्ने">♥</button><p class="quote-text"></p><p class="quote-author"></p><span class="copy-badge">डबल क्लिक गरेर कपी गर्नुहोस्</span>';c.querySelector('.quote-text').textContent=q.quote;c.querySelector('.quote-author').textContent=q.author||'- लक्ष्मण नेपाल';const f=c.querySelector('.favorite-button');f.classList.toggle('active',isFavorite(q));f.onclick=e=>{e.stopPropagation();toggleFavorite(i)};c.ondblclick=()=>copyQuote(i);return c}
function renderQuotes(){scroller.innerHTML='';if(!quotes.length)return;const frag=document.createDocumentFragment();for(let copy=0;copy<3;copy++)quotes.forEach((q,i)=>frag.appendChild(cardHTML(q,i)));scroller.appendChild(frag);observeCards();saveFavorites();requestAnimationFrame(()=>{const cards=scroller.querySelectorAll(`[data-index="${currentQuoteIndex}"]`);(cards[1]||cards[0])?.scrollIntoView({behavior:'auto',block:'center'});updateActiveCards()})}
function toggleFavorite(i){const q=quotes[i],k=quoteKey(q);favorites.has(k)?(favorites.delete(k),showToast('मनपर्नेबाट हटाइयो')):(favorites.add(k),showToast('मनपर्नेमा सुरक्षित भयो'));saveFavorites();scroller.querySelectorAll(`[data-index="${i}"]`).forEach(c=>{c.classList.toggle('favorite-card',favorites.has(k));c.querySelector('.favorite-button').classList.toggle('active',favorites.has(k))})}
async function copyQuote(i=currentQuoteIndex){const q=quotes[i];if(!q)return;const text=`“${q.quote}” ${q.author||''}`;try{await navigator.clipboard.writeText(text)}catch{const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}showToast('उद्धरण कपी भयो ✓')}
function middleCard(i){const cards=scroller.querySelectorAll(`[data-index="${i}"]`);return cards[1]||cards[0]}
function scrollToQuote(i,smooth=true){if(!quotes.length)return;currentQuoteIndex=(i+quotes.length)%quotes.length;middleCard(currentQuoteIndex)?.scrollIntoView({behavior:smooth?'smooth':'auto',block:'center'});updateActiveCards()}
function nextQuote(){scrollToQuote(currentQuoteIndex+1)}function prevQuote(){scrollToQuote(currentQuoteIndex-1)}
function isCentered(c){const a=scroller.getBoundingClientRect(),b=c.getBoundingClientRect();return Math.abs((b.top+b.height/2)-(a.top+a.height/2))<b.height*.45}
function updateActiveCards(){scroller.querySelectorAll('.quote-card').forEach(c=>c.classList.toggle('active',+c.dataset.index===currentQuoteIndex&&isCentered(c)))}
let observer;function observeCards(){if(observer)observer.disconnect();observer=new IntersectionObserver(es=>{let best=null;es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.65){const r=e.target.getBoundingClientRect(),root=scroller.getBoundingClientRect(),d=Math.abs((r.top+r.height/2)-(root.top+root.height/2));if(!best||d<best.d)best={e,d}}});if(best){currentQuoteIndex=+best.e.target.dataset.index;updateActiveCards();if(autoplay&&Date.now()-speechTimer>1200){speechTimer=Date.now();speakCurrent()}}},{root:scroller,threshold:[.65,.8,1]});scroller.querySelectorAll('.quote-card').forEach(c=>observer.observe(c))}
function recenterInfinite(){if(!quotes.length||favoritesMode)return;const max=scroller.scrollHeight-scroller.clientHeight;if(scroller.scrollTop<scroller.clientHeight*.15||scroller.scrollTop>max-scroller.clientHeight*.15){const target=middleCard(currentQuoteIndex);if(target){scroller.style.scrollBehavior='auto';target.scrollIntoView({block:'center'});scroller.style.scrollBehavior='smooth';updateActiveCards()}}}
scroller.addEventListener('scroll',()=>{if(!scroller._edgeFrame)scroller._edgeFrame=requestAnimationFrame(()=>{scroller._edgeFrame=0;recenterInfinite()})});
function startAutoScroll(){clearInterval(autoScrollTimer);if(autoplay)autoScrollTimer=setInterval(nextQuote,7000)}
function toggleAutoplay(){autoplay=!autoplay;if(autoBtn){autoBtn.setAttribute('aria-pressed',autoplay);autoBtn.textContent=autoplay?'⏸ Auto':'▶ Auto'}if(autoplay)startAutoScroll();else{clearInterval(autoScrollTimer);window.speechSynthesis?.cancel()}showToast(autoplay?'Auto चालु भयो':'Auto बन्द भयो')}
function speakCurrent(){if(!('speechSynthesis'in window)){showToast('यो ब्राउजरमा आवाज उपलब्ध छैन');return}const q=quotes[currentQuoteIndex];if(!q)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.quote);u.lang='ne-NP';u.rate=.86;u.pitch=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/^ne(-|_)?NP/i.test(v.lang))||voices.find(v=>/^ne/i.test(v.lang))||null;u.onstart=()=>showToast('पढ्दैछ... 🔊');speechSynthesis.speak(u)}
function toggleFavoritesMode(){favoritesMode=!favoritesMode;document.body.classList.toggle('favorites-mode',favoritesMode);if(favoritesMode&&!favorites.size){showToast('अहिलेसम्म कुनै मनपर्ने छैन');favoritesMode=false;document.body.classList.remove('favorites-mode');return}showToast(favoritesMode?'मनपर्ने उद्धरणहरू':'सबै उद्धरण')}
document.getElementById('next-quote')?.addEventListener('click',nextQuote);document.getElementById('prev-quote')?.addEventListener('click',prevQuote);document.getElementById('copy-quote')?.addEventListener('click',()=>copyQuote());document.getElementById('read-quote')?.addEventListener('click',speakCurrent);document.getElementById('autoplay-toggle')?.addEventListener('click',toggleAutoplay);document.getElementById('favorites-toggle')?.addEventListener('click',toggleFavoritesMode);
async function fetchJSON(path){const r=await fetch(`${path}?v=8`,{cache:'no-store'});if(!r.ok)throw Error(`${path}:${r.status}`);return r.json()}
async function loadQuotes(){try{const results=await Promise.allSettled([fetchJSON('./quotes.json'),fetchJSON('./more-quotes.json')]);const all=[];results.forEach(r=>{if(r.status==='fulfilled'&&Array.isArray(r.value))all.push(...r.value)});const seen=new Set();quotes=all.filter(q=>q&&typeof q.quote==='string'&&q.quote.trim()).map(q=>({...q,quote:q.quote.trim(),author:(q.author||'- लक्ष्मण नेपाल').trim()})).filter(q=>{const k=quoteKey(q);if(seen.has(k))return false;seen.add(k);return true});if(!quotes.length)throw Error('empty');currentQuoteIndex=Math.floor(Math.random()*quotes.length);renderQuotes()}catch(e){console.error(e);scroller.innerHTML='<div class="quote-card active"><p class="quote-text">उद्धरण लोड हुन सकेन।</p></div>';showToast('उद्धरण लोड हुन सकेन')}}loadQuotes();saveFavorites();
